import './globals.css'
import localFont from 'next/font/local'

const myFont = localFont({
  src: [
    {
      path: './segoeui.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './segoeuib.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
